import type { ThemeConfig } from 'antd'

const css = (name: string) => `var(${name})`

const antdToken = {
  colorPrimaryHover: css('--c-primary-400'),
  colorPrimary: css('--c-primary-500'),
  colorPrimaryActive: css('--c-primary-600'),
  colorBgBase: css('--c-background-50'),
  colorBgContainer: css('--c-background-50'),
  colorBorder: css('--c-border-700'),
  colorBorderSecondary: css('--c-border-800'),
  colorTextLightSolid: css('--c-content-50'),
  colorTextQuaternary: css('--c-content-100'),
  colorTextTertiary: css('--c-content-400'),
  colorTextSecondary: css('--c-content-600'),
  colorText: css('--c-content-950'),
  colorSuccessHover: css('--c-success-300'),
  colorSuccess: css('--c-success-500'),
  colorSuccessText: css('--c-success-950'),
  colorWarningHover: css('--c-warning-300'),
  colorWarning: css('--c-warning-500'),
  colorWarningText: css('--c-warning-950'),
  colorErrorHover: css('--c-error-300'),
  colorError: css('--c-error-500'),
  colorErrorText: css('--c-error-950'),
  colorInfoHover: css('--c-info-300'),
  colorInfo: css('--c-info-500'),
  colorInfoText: css('--c-info-950'),
  paddingXXS: css('--s-xs'),
  paddingXS: css('--s-sm'),
  paddingSM: css('--s-md'),
  padding: css('--s-lg'),
  paddingLG: css('--s-xl'),
  paddingXL: css('--s-2xl'),
  fontSizeSM: css('--fs-sm'),
  fontSize: css('--fs-md'),
  fontSizeLG: css('--fs-lg'),
  fontSizeXL: css('--fs-xl'),
  fontSizeHeading3: css('--fs-2xl'),
  fontSizeHeading2: css('--fs-3xl'),
  borderRadiusSM: css('--r-sm'),
  borderRadius: css('--r-md'),
  borderRadiusLG: css('--r-lg'),
  fontWeight: css('--fw-regular'),
  fontWeightStrong: css('--fw-semibold'),
}

export const antdThemeConfig: ThemeConfig = { token: antdToken as unknown as ThemeConfig['token'] }
