import type { ThemeConfig } from 'antd'
import { css } from '../../utils/css'

export const antdThemeConfig: ThemeConfig = {
  token: {
    colorPrimaryHover: css('--c-primary-400'),
    colorPrimary: css('--c-primary-500'),
    colorPrimaryActive: css('--c-primary-600'),
    colorBgBase: css('--c-background-50'),
    colorBgContainer: css('--c-background-50'),
    colorBorder: css('--c-border-700'),
    colorBorderSecondary: css('--c-border-800'),
    colorTextLightSolid: css('--c-content-50'),
    colorTextQuaternary: css('--c-content-100'),
    colorTextTertiary: css('--c-content-400'),
    colorTextSecondary: css('--c-content-600'),
    colorText: css('--c-content-950'),
    colorSuccessHover: css('--c-success-300'),
    colorSuccess: css('--c-success-500'),
    colorSuccessText: css('--c-success-950'),
    colorWarningHover: css('--c-warning-300'),
    colorWarning: css('--c-warning-500'),
    colorWarningText: css('--c-warning-950'),
    colorErrorHover: css('--c-error-300'),
    colorError: css('--c-error-500'),
    colorErrorText: css('--c-error-950'),
    colorInfoHover: css('--c-info-300'),
    colorInfo: css('--c-info-500'),
    colorInfoText: css('--c-info-950'),
    paddingXXS: css('--s-xs', true),
    paddingXS: css('--s-sm', true),
    paddingSM: css('--s-md', true),
    padding: css('--s-lg', true),
    paddingLG: css('--s-xl', true),
    paddingXL: css('--s-2xl', true),
    fontSizeSM: css('--fs-sm', true),
    fontSize: css('--fs-md', true),
    fontSizeLG: css('--fs-lg', true),
    fontSizeXL: css('--fs-xl', true),
    fontSizeHeading3: css('--fs-2xl', true),
    fontSizeHeading2: css('--fs-3xl', true),
    borderRadiusSM: css('--r-sm', true),
    borderRadius: css('--r-md', true),
    borderRadiusLG: css('--r-lg', true),
    fontWeightStrong: css('--fw-semibold', true),
    fontFamily: css('--font-sans'),
  },
}
