import type { ThemeConfig } from 'antd'

export const antdThemeConfig: ThemeConfig = {
  token: {
    colorPrimaryHover: 'var(--c-primary-400)',
    colorPrimary: 'var(--c-primary-500)',
    colorPrimaryActive: 'var(--c-primary-600)',
    colorBgBase: 'var(--c-background-50)',
    colorBgContainer: 'var(--c-background-50)',
    colorBorder: 'var(--c-border-700)',
    colorBorderSecondary: 'var(--c-border-800)',
    colorTextLightSolid: 'var(--c-content-50)',
    colorTextQuaternary: 'var(--c-content-100)',
    colorTextTertiary: 'var(--c-content-400)',
    colorTextSecondary: 'var(--c-content-600)',
    colorText: 'var(--c-content-950)',
    colorSuccessHover: 'var(--c-success-300)',
    colorSuccess: 'var(--c-success-500)',
    colorSuccessText: 'var(--c-success-950)',
    colorWarningHover: 'var(--c-warning-300)',
    colorWarning: 'var(--c-warning-500)',
    colorWarningText: 'var(--c-warning-950)',
    colorErrorHover: 'var(--c-error-300)',
    colorError: 'var(--c-error-500)',
    colorErrorText: 'var(--c-error-950)',
    colorInfoHover: 'var(--c-info-300)',
    colorInfo: 'var(--c-info-500)',
    colorInfoText: 'var(--c-info-950)',
    paddingXXS: 4,
    paddingXS: 8,
    paddingSM: 12,
    padding: 16,
    paddingLG: 24,
    paddingXL: 32,
    fontSizeSM: 14,
    fontSize: 16,
    fontSizeLG: 18,
    fontSizeXL: 20,
    fontSizeHeading3: 24,
    fontSizeHeading2: 30,
    borderRadiusSM: 4,
    borderRadius: 8,
    borderRadiusLG: 12,
    fontWeightStrong: 600,
    fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif',
  },
}
