# Flox project configuration
schema = 1

[project]
name = "Postify"

[user]
name = "Isaac"
conversation_language = "pt-BR"
file_language = "pt-BR"

[install]
modules = ["core", "software-dev"]
skills = []
providers = ["claude", "codex"]

[workflow]
git_flow = true

[setup]
schema = 1
state = "valid"
last_validated_at = "2026-09-16"
references = ["project-context.md", "artifacts/planning/pentest/PENTEST-ROADMAP.md", "artifacts/planning/quality/QUALITY-ROADMAP.md", "artifacts/planning/release/RELEASE-ROADMAP.md", "artifacts/planning/git/GIT-ROADMAP.md"]
reference_fingerprint = [{ path = "", type = "directory", dev = 16777243, ino = 22294526 }, { path = "project-context.md", type = "file", dev = 16777243, ino = 23056772, hash = "6cbd4f609d35113b45be7d3ecf739db0220aec3fdc67883413b67b88e93c1045" }, { path = "artifacts", type = "directory", dev = 16777243, ino = 22294527 }, { path = "artifacts/planning", type = "directory", dev = 16777243, ino = 22295002 }, { path = "artifacts/planning/pentest", type = "directory", dev = 16777243, ino = 22295003 }, { path = "artifacts/planning/pentest/PENTEST-ROADMAP.md", type = "file", dev = 16777243, ino = 22295004, hash = "a08a34bd346d34cbf0847feeade2971faa9a3ea134071c6f1a0b8a03a8acf485" }, { path = "artifacts", type = "directory", dev = 16777243, ino = 22294527 }, { path = "artifacts/planning", type = "directory", dev = 16777243, ino = 22295002 }, { path = "artifacts/planning/quality", type = "directory", dev = 16777243, ino = 22295006 }, { path = "artifacts/planning/quality/QUALITY-ROADMAP.md", type = "file", dev = 16777243, ino = 23056773, hash = "f531f61bc378b83908189233cf53aefe8dbd49662810687047e99a1bd7602294" }, { path = "artifacts", type = "directory", dev = 16777243, ino = 22294527 }, { path = "artifacts/planning", type = "directory", dev = 16777243, ino = 22295002 }, { path = "artifacts/planning/release", type = "directory", dev = 16777243, ino = 22295009 }, { path = "artifacts/planning/release/RELEASE-ROADMAP.md", type = "file", dev = 16777243, ino = 22295062, hash = "e05bb982a333baf81dc18539ee31e3cf155e60b005cfb5c0e67094fcef8831db" }, { path = "artifacts", type = "directory", dev = 16777243, ino = 22294527 }, { path = "artifacts/planning", type = "directory", dev = 16777243, ino = 22295002 }, { path = "artifacts/planning/git", type = "directory", dev = 16777243, ino = 22295011 }, { path = "artifacts/planning/git/GIT-ROADMAP.md", type = "file", dev = 16777243, ino = 22345534, hash = "625d9439a8ad21d1f9dd1c3edfecb792d05d36284379f56d99c93dc82278e8ac" }]
